flowchart TD

start((API Client))

subgraph gRPC_server
    unary["`
            **Unary**
            ListNaming()
            Resolve()
            Invoke()
            `"]
            
    config["`
            **Config**
            GetProperty()
            SetProperty()
            SubscribeConfig()
            `"]
    
    subscription["`
            **Subscription**
            SubscribeAlarms()
            SubscribeLogs()
            SubscribeMonitor()
            `"]
end

subgraph "UnaryManager"
    NS
    IFR
    DII["`
        DII
        DeviceDispatcher
        `"]
    Config
end

subgraph SubscriptionManager
    ConfigManager
    AlarmManager
    LogManager
    MonitorManager
end

subgraph CorbaServant
    AlarmConsumer
    ConfigConsumer
    MonitorConsumer
    LogConsumer
end

subgraph TypeAdapter
    LogAdapter
    AlarmAdapter
    MonitorAdapter
    ConfigAdapter
    AnyAdapter
end

subgraph SubscriptionRegistry
    ConfigRegistry
    AlarmRegistry
    LogRegistry
    MonitorRegistry
end

subgraph SubscriptionPropagator
    ConfigPropagator
    AlarmPropagator
    LogPropagator
    MonitorPropagator
end

start --> gRPC_server
gRPC_server --> CorbaRuntime
CorbaRuntime --Invoke()--> DII
DII --Get interface--> IFR
DII --Convert to/from CORBA Objects--> TypeAdapter
CorbaRuntime --Resolve()--> IFR
IFR --get device IOR--> NS
IFR --Convert from CORBA Objects--> TypeAdapter
CorbaRuntime --Get/SetProperty()--> Config
CorbaRuntime --ListNaming()--> NS
Config <--Access to get/set properties---> ConfigManager
CorbaRuntime --All subscriptions--> SubscriptionManager
SubscriptionManager --Register/Unregister subscription with token--> SubscriptionRegistry
SubscriptionManager <--Obtain Consumer Object to subscribe--> CorbaServant
SubscriptionManager <--subscribe()/unsubscribe() with Consumer object--> SubscriptionPropagator
CorbaServant --Send new converted data when is avaliable--> SubscriptionRegistry
CorbaServant <--Convert to/from CORBA Objects---> TypeAdapter
